### ISSUE TITLE
+org-roam-node-list

### ISSUE THREAD

**Issue by dmgerman** [akashpal-21/org-roam-utilities#2]
don't silently remove slots without a mapping

in "cl-remove-if 'null".

raise an error instead. If a column does not exist, it is most likely an error.

**Comment by akashpal-21** [comment]
It was originally intended to remove the nil generated from the `&optional` in the slot list - as a side effect it silently removes any wrongly set slot. 

if we have `(id &optional file-title)` and so on - here id, &optional and file-title will be checked in the mapping -- the &optional will return a nil nevertheless and we should silently remove this. This is just a required processing logic.

We can raise an error for other types of mismatch but this will increase the code complexity - i suspect it is not worth warning the user here - the user would be automatically made aware that they have done a typo when they try to use the required accessor function to access the slot.
