### ISSUE TITLE
don't hard code faces

### ISSUE THREAD

**Issue by dmgerman** [akashpal-21/org-roam-utilities#5]
`(propertize (org-roam-node-title node) 'face 'bold))))
`

would it no better to define a face for this purpose instead of hardcoding it?

**Comment by akashpal-21** [comment]
Yes - but I intend it to be altered by the user, it is just an example that I use - I always have this face for it so I never required to define a face for it.

I intend that the entire function of display template be customised by the user - so its not hardcored at all. Think of the function as a variable.
